[package]
name = "sui_fusion_plus"
edition = "2024.beta"
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
sui_fusion_plus = "0x0"

[dev-addresses]
sui_fusion_plus = "0x0"

